language: node_js

node_js:
  - "10"
  - "11"

install:
  - npm i
  - npm run bootstrap
  - npm run build # @TODO lerna bug will use symlink when depending on internal packages, but package is typescript, no lib before build

script:
  - npm run test

after_success:
  # - npm run coverage
  - git remote set-url origin git@${GH_TOKEN}@github.com:${TRAVIS_REPO_SLUG}.git

git:
  depth: 5

cache:
  directories:
    - node_modules

before_deploy:
  - cp .npmrc.template ~/.npmrc

deploy:
  provider: script
  email: olivier.albertini@montreal.ca
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  script: npx lerna publish --yes
  on:
    tags: true
    branch: master