/*!
 * Copyright (c) 2019 Ville de Montreal. All rights reserved.
 * Licensed under the MIT license.
 * See LICENSE file in the project root for full license information.
 */
export const logo = `
MMMMMMMMMMN0o:;;;;;;cxXWWXxc;;;;;;:o0WMMMMMMMMMM
MMMMMMMMWXo;;dOKXXKkl;:ll:;okKXXKOo;;dXMMMMMMMMM
MMMMMMMMNd'c0WMMMMMMNx;..;kNMMMMMMW0:,xNMMMMMMMM
MMMMMMMMKc'dWMMMMMMMMKc.'lXMMMMMMMMNd'lXMMMMMMMM
MMWX0kxdo;'lXWMMMMMMMKc''oXMMMMMMMWKl';oxxk0XWMM
N0o:;clll:,'lk0KNWMMMKc''oXMMMWXK0kc',:cllc;:o0W
d;;d0NWWWXOl''',:kNMMKc''oNMMNx:,'',lONWWWN0d;;x
,,xNMMMMMMWO;....cXMMXc''oNMMKc....;OWMMMMMMNx,;
.:0MMMMMMMMNkc;:l0WMMXc''oNMMNOl::lkNMMMMMMMW0;'
;,dNMMMMMMMMMNXNWMMMMKc''lXMMMMWNNWMMMMMMMMWXd,:
O:,lkKXXXXXXXNXXNNNXXx;..;kKXXXXXNNXNXXXXXKkc,cO
WKo,',;:::::::::::::;'....';:::::::::::::;,',oKW
Xx:;cdxkkkkkkOkkkkkkdc'..'cxkkkkkkkkkkkkkxdc,:xX
l,cONWMMMMMMMMMMMMMMWKc.'cKWMMMMMMMMMMMMMMWNOc,o
';OWMMMMMMMWXOxxONMMMXc''oXMMMNOxxkXWMMMMMMMWO;,
';OWMMMMMMMKc'..,dNMMXl''oNMMXo'..'cKMMMMMMMWO;,
c,l0WMMMMMNx,...'oNMMXl''oNMMXo'...,xNMMMMMW0c,l
Ko;;oxOOOxl,,codkXWMMXl''oXMMWXkdoc,,lxkOOxl;;dK
MW0xlc:::,.:ONWMMMMMMXl''oXMMMMMMWNO:.,:::coxKWM
MMMMWNXXO:'dNMMMMMMMMKc''oXMMMMMMMMWd'l0XXNWMMMM
MMMMMMMMXl'oNMMMMMMMW0:..:0WMMMMMMWXo'oNMMMMMMMM
MMMMMMMMWO:,oKWMMMWNOc''''cONWMMMN0o,:0WMMMMMMMM
MMMMMMMMMW0o;;ldddoc;:xOOd:;coddoc;;oKWMMMMMMMMM
MMMMMMMMMMMNOl;'..,cdKWMMWKd:,'.';oONMMMMMMMMMMM
`;
